### ISSUE TITLE
The Top 3 Data Science Books

### ISSUE THREAD

**Issue by ABDaSci** [MrMimic/data-scientist-roadmap#37]
Which data science books would you recommend for someone starting a career in data science?

- Your top 3 books that give good practical working knowledge of how to operate effectively on the job.

**Comment by MrMimic** [comment]
Hey,
Honestly, none (if you don't plan to become a researcher). At the moment, the market seems to turn in favor of people having very good development skills, rather than huge theoretical mathematical or statistical knowledge. Less and less models are actually trained by teams (talking outside of the academical world), while pre-trained or foundation models can easily be used by developers, devops, etc.
So instead of getting practical knowledge in books, I'd rather recommend to learn how to dev effectively, computing science fundamentals (algorithms, CICDs, APIs, etc) and then, jump into projects mainly on dirty data (Kaggle is nice, but you'll never be working on such clean datasets in the real world). And programming is not fun when learnt on books instead of pratice.
